---
title: "Death Days"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(data.table)
library(tidyverse)
```


```{r read_data, cache = TRUE}
# We are using the data.table package because it is faster. Note how it also
# provides a handier error message about the bad line in the file.

x <- data.table::fread("~/bunmd_v2.csv") %>% 
  as_tibble() %>% 
  select(ssn, lname, dyear, dmonth, dday, byear, bmonth, bday)
```


```{r}
small <- x %>%
  slice_sample(prop = 0.01)

```


```{r}
small %>%
  drop_na(dday) %>%
  ggplot(mapping = aes(x = dday)) +
  geom_bar() +
  labs(title = "Deaths by Day of the Month",
       subtitle = "Suspicious Number of Deaths on the 15th"
        )
```

```{r death_ratios}

small %>%
  filter(dday %in% c(1, 2)) %>%
  group_by(dyear, dday) %>%
  summarize(deaths = n(),
            .groups = "drop") %>%
  pivot_wider(names_from = dday,
              values_from = deaths) %>%
  mutate(ratio = `1` / `2`) %>%
  ggplot(aes(x = dyear,
             y = ratio)) +
  geom_point()

```


